version: '3.1'
services:
  db:
    image: postgres:14.5
    restart: "no"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile-local
    environment:
      DATABASE_USERNAME: 'postgres'
      DATABASE_PORT: '5432'
      DATABASE_HOST: 'db'
      DATABASE_PASSWORD: 'example'
      DECIDIM_APPLICATION_NAME: 'Recharge'
      DECIDIM_MAILER_SENDER: 'recharge@platoniq.net'
      DECIDIM_AVAILABLE_LOCALES: 'en, it'
      DECIDIM_ENABLE_HTML_HEADER_SNIPPETS: 'false'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - gems:/usr/local/bundle:delegated
      - ~/.ssh/:/root/.ssh  #for deploy enter bash and run "eval $(ssh-agent -s)" and "ssh-add"
      - .:/decidim-recharge
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - db

volumes:
  db: {}
  gems: {}
